/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-2",
  "aws_cognito_identity_pool_id": "us-west-2:84360e44-bbe5-4688-83f8-3cd01f515a75",
  "aws_cognito_region": "us-west-2",
  "aws_user_pools_id": "us-west-2_cl1TOHaIA",
  "aws_user_pools_web_client_id": "4o31i95liloomnqoe2r2qpiaqe",
  "oauth": {
    "domain": "waifu-management-prod.auth.us-west-2.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "https://waifu-management.assets.unthrottled.io/oauth/callback/,http://localhost:3000/oauth/callback/",
    "redirectSignOut": "https://waifu-management.assets.unthrottled.io/oauth/logout/,http://localhost:3000/oauth/logout/",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_content_delivery_bucket": "aifussetanagement-20201106051158-hostingbucket-prod",
  "aws_content_delivery_bucket_region": "us-west-2",
  "aws_content_delivery_url": "https://dci6fqglfy821.cloudfront.net"
};


export default awsmobile;
